# Use an official Node.js image as the base image
FROM node:16 AS development

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json to the working directory
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY frontend ./

# Expose the development server port
EXPOSE 5173

# Use a shell form of CMD to start the development server
CMD ["npm", "run", "dev"]
